### ISSUE TITLE
What happened to spec.load_and_resolve_spec?

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#108]
@FynnBe we used to have this function to load the spec from a yaml and build the spec object. But now:
```
$ python -c "import bioimageio.spec as spec; spec.load_and_resolve_spec"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'bioimageio.spec' has no attribute 'load_and_resolve_spec'
```
Did you rename this function?

**Comment by constantinpape** [comment]
I guess it's 
https://github.com/bioimage-io/spec-bioimage-io/blob/master/bioimageio/spec/v0_3/utils.py#L55

But when I try it I get the following error (also it's clear from the returnval / function signature of `resolve_raw_node_to_node`):
```
  File "/g/kreshuk/pape/Work/bioimageio/spec-bioimage-io/bioimageio/spec/v0_3/utils.py", line 56, in load_model
    return resolve_raw_node_to_node(*load_raw_model(source, root_path=root_path))
TypeError: resolve_raw_node_to_node() missing 1 required positional argument: 'nodes_module'
```

**Comment by FynnBe** [comment]
yes I renamed it `load_model` (to keep the analogy to raw_nodes/nodes there is load_raw_model/load_model). 
hopefully da2510769c7c36d8034e046fcaa70c571573fd51 solves this. apparently we are lacking some tests that would cover `load_module`...

**Comment by constantinpape** [comment]
Ok, I made it work with the latest commit, but had to fix two more issues:

It looks like "root_path" is not really optional, if I don't pass it I get the following error:
```
Traceback (most recent call last):                                                                                                          
  File "export_bioimageio_model.py", line 104, in <module>                                                                                  
    export_to_bioimageio(args.checkpoint, args.input, args.output,                                                                          
  File "export_bioimageio_model.py", line 84, in export_to_bioimageio                                                                       
    export_biomageio_model(                                                                                                                 
  File "/home/pape/Work/software/conda/miniconda3/envs/torch17/lib/python3.8/site-packages/torch_em/util/modelzoo.py", line 557, in export_b
iomageio_model                                                                                                                              
    val_success = _validate_model(out_path)                                                                                                 
  File "/home/pape/Work/software/conda/miniconda3/envs/torch17/lib/python3.8/site-packages/torch_em/util/modelzoo.py", line 469, in _validat
e_model                                                                                                                                     
    model, normalizer, bio_spec = import_bioimageio_model(spec_path, return_spec=True)                                                      
  File "/home/pape/Work/software/conda/miniconda3/envs/torch17/lib/python3.8/site-packages/torch_em/util/modelzoo.py", line 693, in import_b
ioimageio_model                                                                                                                             
    bio_spec = spec.load_model(os.path.abspath(spec_path))                                                                                  
  File "/g/kreshuk/pape/Work/bioimageio/spec-bioimage-io/bioimageio/spec/v0_3/utils.py", line 56, in load_model                             
    return resolve_raw_node_to_node(*load_raw_model(source, root_path=root_path), nodes_module=nodes)                                       
  File "/g/kreshuk/pape/Work/bioimageio/spec-bioimage-io/bioimageio/spec/shared/transformers.py", line 249, in resolve_raw_node_to_node     
    node = UriNodeTransformer(root_path=root_path).transform(raw_node)                                                                      
  File "/g/kreshuk/pape/Work/bioimageio/spec-bioimage-io/bioimageio/spec/shared/transformers.py", line 93, in __init__                      
    self.python_path = self._guess_python_path_from_local_spec_path(root_path=root_path)                                                    
  File "/g/kreshuk/pape/Work/bioimageio/spec-bioimage-io/bioimageio/spec/shared/transformers.py", line 124, in _guess_python_path_from_local
_spec_path                                                                                                                                  
    if (path / "manifest.yaml").exists() or (path / "manifest.yml").exists():                                                               
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'   
```

>  apparently we are lacking some tests that would cover `load_module`

Yes, we definitely need tests for this.

**Comment by FynnBe** [comment]
> It looks like "root_path" is not really optional, if I don't pass it I get the following error:

yeah, that's a bit unfortunate. right now root_path is only really optional, if source is a dict, but otherwise it is required to resolve relative paths specified in source. (That it expects no relative paths in dict is also a silent assumption 😞 )

**Comment by constantinpape** [comment]
> yeah, that's a bit unfortunate. right now root_path is only really optional, if source is a dict, but otherwise it is required to resolve relative paths specified in source. (That it expects no relative paths in dict is also a silent assumption disappointed )

Can we explicitly check for this and raise a meaningful ValueError if the conditions are not met?

**Comment by k-dominik** [comment]
ran into this, too :)
