### ISSUE TITLE
TorchScript model deepImageJ

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#128]
Hi, here is the error given by Fiji:
```
ai.djl.engine.EngineException: [enforce fail at inline_container.cc:222] . file not found: archive/constants.pkl
at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method)
at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1247)
at ai.djl.pytorch.engine.PtModel.load(PtModel.java:78)
at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:142)
at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:169)
at deepimagej.stamp.LoadPytorchStamp.run(LoadPytorchStamp.java:231)
at java.lang.Thread.run(Thread.java:748)
```
@constantinpape, could you please try to export it using PyTorch 1.6?

**Comment by constantinpape** [comment]
We have working torchscript models now, so I'm gonna close this one.
