### ISSUE TITLE
CLI does not work

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#160]
Using the CLI command does not work:
```
$ bioimageio
Traceback (most recent call last):
  File "/home/pape/Work/software/conda/miniconda3/envs/torch19/bin/bioimageio", line 33, in <module>
    sys.exit(load_entry_point('bioimageio.spec', 'console_scripts', 'bioimageio')())
  File "/home/pape/Work/software/conda/miniconda3/envs/torch19/bin/bioimageio", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch19/lib/python3.9/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'bioimageio.spec' has no attribute 'main'
```

The problem is that the entry point https://github.com/bioimage-io/spec-bioimage-io/blob/main/setup.py#L40 does not exist.

There is a nice blogpost on how to do this properly with typer:
https://jrwalk.github.io/pages/projects/python-cli-utilities-poetry-typer

**Comment by FynnBe** [comment]
nice, I'll add this right away. It does boil down to replacing
```python
if __name__ == "__main__":
    app()
```
    
 with

```python
def main():
    app()
```
