### ISSUE TITLE
verify model config files - ruamel.yaml dependency

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#259]
Hi!

I'm not sure of this part of the validator is supported but I get the following error message [here](https://github.com/deepimagej/models/runs/3930902817#step:7:58):

RuntimeError: Cannot read RDF from manifest.bioimage.ya... without ruamel.yaml dependency!
Error: Process completed with exit code 1.

We are uding this validator as a [github workflow for our models](https://github.com/deepimagej/models/blob/master/.github/workflows/compile-manifest.yml#L41). 

Thank you!

**Comment by constantinpape** [comment]
You need to install ruamel.yaml as additional dependency. see https://pypi.org/project/ruamel.yaml/.
Note that this is deliberately left out of the `requirements.txt` in order to enable running `bioimageio.spec` in pyodide.

**Comment by esgomezm** [comment]
I added the dependency but still it outputs an error message that I don't know how to solve it: 

```
Run pip install git+https://github.com/bioimage-io/spec-bioimage-io.git
Collecting git+https://github.com/bioimage-io/spec-bioimage-io.git
  Cloning https://github.com/bioimage-io/spec-bioimage-io.git to /tmp/pip-req-build-u79dpdi9
  Running command git clone --filter=blob:none -q https://github.com/bioimage-io/spec-bioimage-io.git /tmp/pip-req-build-u79dpdi9
  Resolved https://github.com/bioimage-io/spec-bioimage-io.git to commit 8f5396652723a462d604a4f57ba5fdaefc7ce10d
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing wheel metadata (pyproject.toml): started
  Preparing wheel metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: marshmallow-jsonschema in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (0.12.0)
Requirement already satisfied: typer in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (0.4.0)
Requirement already satisfied: PyYAML>=5.2 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (6.0)
Requirement already satisfied: typing-extensions in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (3.10.0.2)
Requirement already satisfied: marshmallow<4.0,>=3.6.0 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (3.14.0)
Requirement already satisfied: imageio>=2.5 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (2.9.0)
Requirement already satisfied: requests in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (2.26.0)
Requirement already satisfied: marshmallow-union in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from bioimageio.spec==0.3.3.post4) (0.1.15.post1)
Requirement already satisfied: pillow in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from imageio>=2.5->bioimageio.spec==0.3.3.post4) (8.4.0)
Requirement already satisfied: numpy in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from imageio>=2.5->bioimageio.spec==0.3.3.post4) (1.21.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from requests->bioimageio.spec==0.3.3.post4) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from requests->bioimageio.spec==0.3.3.post4) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from requests->bioimageio.spec==0.3.3.post4) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from requests->bioimageio.spec==0.3.3.post4) (2021.10.8)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from typer->bioimageio.spec==0.3.3.post4) (8.0.3)
Requirement already satisfied: importlib-metadata in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from click<9.0.0,>=7.1.1->typer->bioimageio.spec==0.3.3.post4) (4.8.1)
Requirement already satisfied: zipp>=0.5 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from importlib-metadata->click<9.0.0,>=7.1.1->typer->bioimageio.spec==0.3.3.post4) (3.6.0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/bioimageio", line 8, in <module>
    sys.exit(app())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bioimageio/spec/__main__.py", line 24, in validate
    summary = commands.validate(rdf_source, update_format, update_format_inner)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bioimageio/spec/commands.py", line 36, in validate
    rdf_source, source_name, root = resolve_rdf_source(rdf_source)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bioimageio/spec/io_.py", line 134, in resolve_rdf_source
    assert isinstance(source, dict)
AssertionError
Error: Process completed with exit code 1.
```

**Comment by esgomezm** [comment]
Yes, all the models have a model.yaml because that's the file we load in deepImageJ as the name changed right after we released the stable version.

**Comment by FynnBe** [comment]
#265 contineus the discussion on the `full` extra, everything else looks settled, please reopen otherwise
