### ISSUE TITLE
Errors for manifest.bioimage.yaml

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#266]
Hi again, 

now the error has changed but I cannot really know where it comes from: https://github.com/deepimagej/models/runs/3963723727#step:7:34

```
Requirement already satisfied: zipp>=0.5 in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (from importlib-metadata->click<9.0.0,>=7.1.1->typer->bioimageio.spec==0.3.3.post5) (3.6.0)
Errors for manifest.bioimage.yaml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/bioimageio", line 8, in <module>
    sys.exit(app())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bioimageio/spec/__main__.py", line 27, in validate
    pprint(summary["errors"])
KeyError: 'errors'
Error: Process completed with exit code 1.
```

Thank you!

**Comment by FynnBe** [comment]
0.3.3post6 is now available via pip
