### ISSUE TITLE
Creation of processing operations

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#588]
The creation of (Pre)processing descriptions does not work as I would expect it.

I would expect the following code to work:

```python
from bioimageio.spec.model.v0_5 import ScaleLinearDescr
from bioimageio.spec.model.v0_5 import ZeroMeanUnitVarianceDescr

# THIS WORKS
ScaleLinearDescr(kwargs={"gain": 1.1, "offset": 0.0})

# THIS FAILS
ZeroMeanUnitVarianceDescr(kwargs={"mode": "per_sample", "axes": "cyx", "mean": None, "std": None})
```

However, only the `ScaleLinearDescr` works. 

`ZeroMeanUnitVarianceDescr` fails with these validation errors:

```
Traceback (most recent call last):
  File "/home/pape/Work/my_projects/torch-em/mre.py", line 8, in <module>
    ZeroMeanUnitVarianceDescr(kwargs={"mode": "per_sample", "axes": "cyx", "mean": None, "std": None})
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for ZeroMeanUnitVarianceDescr
kwargs.axes
  'str' instances are not allowed as a Sequence value [type=sequence_str, input_value='cyx', input_type=str]
kwargs.mode
  Extra inputs are not permitted [type=extra_forbidden, input_value='per_sample', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
kwargs.mean
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
kwargs.std
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
```

It's unclear to me why this fails since all these values should be valid according to https://github.com/bioimage-io/spec-bioimage-io/blob/main/bioimageio/spec/model/v0_4.py#L599 .

**Comment by constantinpape** [comment]
Ok, that fixes it. Thanks!
